name: appimage2deb-ubuntu2204

on: workflow_dispatch

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  # This yml is copied from https://github.com/hn-88/OCVWarp/blob/master/.github/workflows/cmake-nix.yml
  # and modified.
  BUILD_TYPE: Release
  # As recommended here: https://github.com/marketplace/actions/sccache-action
  OPENSPACE_VERSION: "0.20.1"
  APPIMAGE_VERSION: "1"
  
jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    
    - name: get openspace appimage for a particular release
      # https://github.com/zhiyuan1i/appimage2deb
      # https://github.com/hn-88/OpenSpace-AppImage
      # https://www.reddit.com/r/linuxquestions/comments/nb0x1m/how_to_convert_appimages_to_deb_files/
      run: |
        openSpaceHome="$HOME/source/OpenSpace"
        git clone https://github.com/zhiyuan1i/appimage2deb.git "$openSpaceHome"
        cd "$openSpaceHome"
        echo "Installing appimage2deb.deb ..."
        sudo dpkg -i appimage2deb.deb
        echo "Downloading appimage ..."
        wget https://github.com/hn-88/OpenSpace-AppImage/releases/download/${OPENSPACE_VERSION}-${APPIMAGE_VERSION}/OpenSpace-${OPENSPACE_VERSION}-${APPIMAGE_VERSION}-x86_64.AppImage
        echo "Converting appimage to deb ..."
        appimage2deb 
        

    - name: Upload deb Artifact
      uses: actions/upload-artifact@v4
      with:
        # Artifact name
        name: OpenSpace-AppImage
        # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: $HOME/source/OpenSpace/OpenSpace*.deb
      
    
